# Site settings
title: Ali Saraer
description: PhD Candidate | AI for Physics
baseurl: "" # Leave this empty for a personal website
url: "https://as2c.github.io"

# Author details
author:
  name: "Ali Saraer"
  avatar: "/assets/images/avatar.jpg" # Replace with your profile picture
  bio: "PhD Candidate at the University of Toronto specializing in AI for Physics."
  location: "Waterloo, Canada"
  links:
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/as2c"
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "https://linkedin.com/in/ali-saraer"

# Theme settings
theme: "minimal-mistakes"
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-archives
  - jekyll-paginate

# Navigation links
header_pages:
  - index.md
  - research.md
  - publications.md
  - talks.md
  - contact.md

# Social sharing
twitter_username: ali_saraer
github_username: as2c

# Markdown settings
markdown: kramdown
highlighter: rouge
